CREATE TABLE plant_2(
	DATE_TIME TEXT,
	PLANT_ID INTEGER,
	SOURCE_KEY TEXT,
	DC_POWER DOUBLE PRECISION,
	AC_POWER DOUBLE PRECISION,
	DAILY_YIELD DOUBLE PRECISION,
	TOTAL_YIELD DOUBLE PRECISION
);